<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x86</PlatformTarget>
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
    <RootNamespace>MRDAttendanceCollector</RootNamespace>
    <UserSecretsId>dotnet-MRDAttendanceCollector-373f6080-60ac-44e2-964a-49a1df69af67</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cronos" Version="0.8.4" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.EventLog" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Interop.zkemkeeper">
      <HintPath>Libs\Interop.zkemkeeper.dll</HintPath>
      <Private>True</Private>
      <EmbedInteropTypes>False</EmbedInteropTypes>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="Libs\SDK-SETUP.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Libs\Register_SDK_x86.bat" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Libs\*.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Libs\%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>

</Project>
